[project]
name = "pii-detector"
version = "0.1.0"
description = "PII detection"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=5.13.0",
    "spacy>=3.4.0",
    "spacy-curated-transformers",
]
