name: Test Binary Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    name: Test Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
          echo "$HOME\.cargo\bin" >> $GITHUB_PATH
        else
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        fi
      shell: bash

    - name: Install dependencies
      run: |
        uv sync
      shell: bash

    - name: Test build process
      run: |
        uv run python build_binary.py
      shell: bash
      env:
        CI: true

